name: CI/CD

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout codigo
    uses: actions/checkout@v4

  - name: Deploy via SSH
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: 137.131.154.8
      username: ubuntu
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      script: |
        echo "Deploy funcionando"